label: Castellano
pages:
    -
        label: The Black Hack
        author: Rafael Pardo Macías
        version: '0.5'
        filename: the-black-hack.md
    -
        label: Additional Things
        author: Rafael Pardo Macías
        version: '0.1'
        filename: additional-things.md
